includes:
- ./text.yaml
- configs/datasets/memes/bert.yaml
- configs/models/unimodal/bert.yaml

model_config:
  unimodal_text:
    num_labels: 6
    classifier:
      type: mlp
      params:
        in_dim: 768
        num_layers: 2
        out_dim: 6

training:
  batch_size: 16